using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Threading;
using System.IO;
using System.Diagnostics;

namespace loader
{
    class Program
    {
        static void Main(string[] args)
        {

            Console.WriteLine("───▄▀▀▀▄▄▄▄▄▄▄▀▀▀▄───");
            Console.WriteLine("───█▒▒░░░░░░░░░▒▒█───");
            Console.WriteLine("────█░░█░░░░░█░░█────");
            Console.WriteLine("─▄▄──█░░░▀█▀░░░█──▄▄─");
            Console.WriteLine("█░░█─▀▄░░░░░░░▄▀─█░░█");
            Console.WriteLine("--------------------------------------------------------------------------------");
            Console.WriteLine("██╗░░░░░░█████╗░░█████╗░██████╗░███████╗██████╗░  ██╗░░░██╗░░░░░███╗░░░░░░█████╗");
            Console.WriteLine("██║░░░░░██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗  ██║░░░██║░░░░████║░░░░░██╔══██╗");
            Console.WriteLine("██║░░░░░██║░░██║███████║██║░░██║█████╗░░██████╔╝  ╚██╗░██╔╝░░░██╔██║░░░░░██║░░██║");
            Console.WriteLine("██║░░░░░██║░░██║██╔══██║██║░░██║██╔══╝░░██╔══██╗  ░╚████╔╝░░░░╚═╝██║░░░░░██║░░██║");
            Console.WriteLine("███████╗╚█████╔╝██║░░██║██████╔╝███████╗██║░░██║  ░░╚██╔╝░░██╗███████╗██╗╚█████╔╝");
            Console.WriteLine("╚══════╝░╚════╝░╚═╝░░╚═╝╚═════╝░╚══════╝╚═╝░░╚═╝  ░░░╚═╝░░░╚═╝╚══════╝╚═╝░╚════╝░");
            Console.WriteLine("--------------------------------------------------------------------------------");
            Console.WriteLine("Start Updating...");
            Thread.Sleep(2000);
            File.Delete("getData_App.exe");
            Console.WriteLine("Delete OLD File...");
            File.Copy(@"\\192.168.10.254\ShareFolder\temp\ARI RAJA\Get_Data\getData_App.exe", "getData_App.exe", true);
            Console.WriteLine("Copy Updated File...");
            Thread.Sleep(1000);
            Console.WriteLine("something gone wrong");
            Thread.Sleep(1000);
            Console.WriteLine("try to delete your file...");
            Thread.Sleep(1000);
            Console.WriteLine("deleting file...");
            Thread.Sleep(3000);
            Console.WriteLine("just juke man...");
            Thread.Sleep(1000);
            Console.Clear();
            Console.ForegroundColor = ConsoleColor.Green;
            //Console.WriteLine("┼┼║┼┼┼║┼║┼║┼║┼║┼║┼║┼▒██┼┼┼║┼║┼║┼║┼║┼┼┼║┼║┼║┼┼");
            //Console.WriteLine("┼┼┼┼┼║┼║┼┼┼║┼║┼┼┼┼┼█████║║┼┼┼┼┼║┼┼┼║┼║┼┼┼║┼┼┼");
            //Console.WriteLine("┼┼┼┼║┼┼┼┼┼║┼┼┼║┼┼┼███████▒┼┼║┼┼┼┼┼║┼║┼║┼║┼║┼┼");
            //Console.WriteLine("┼║┼║┼║┼┼┼┼┼║┼║┼┼┼█████████║║┼║┼┼┼║┼┼┼║┼┼┼║┼┼┼");
            //Console.WriteLine("┼┼┼┼║┼┼┼║┼║┼║┼┼┼███████████┼║┼┼┼┼┼┼┼║┼┼┼┼┼┼┼║");
            //Console.WriteLine("┼┼┼┼┼┼┼┼┼║┼┼┼┼┼║████████████┼┼┼║┼┼┼┼┼┼┼║┼║┼┼┼");
            //Console.WriteLine("┼┼║┼┼┼┼┼┼┼┼┼║┼║▒████████████▒┼║┼║┼┼┼┼┼║┼║┼┼┼┼");
            //Console.WriteLine("┼║┼┼┼┼┼║┼║┼┼┼║┼██████████████║┼║┼║┼║║█████┼┼┼");
            //Console.WriteLine("┼┼┼┼║┼║┼┼┼║┼┼┼║█████████████████▒┼▒████████┼║");
            //Console.WriteLine("┼┼┼┼┼║┼║┼┼┼┼┼║▒████████████████████████████▒┼");
            //Console.WriteLine("║┼║┼┼┼║┼┼┼┼┼████████████████████████████████║");
            //Console.WriteLine("┼║┼┼┼║┼┼┼┼▒█████████████████████████████████║");
            //Console.WriteLine("║┼║┼┼┼║┼║█████▒┼█████████████████████████████");
            //Console.WriteLine("┼┼┼┼┼┼┼┼████▒┼┼║█████████████████████████████");
            //Console.WriteLine("║┼┼┼┼┼║████┼┼┼┼┼█████████████████████████████");
            //Console.WriteLine("┼┼┼║┼║███▒┼║┼║┼║█████████████████████████████");
            //Console.WriteLine("║┼║┼┼███▒┼┼┼║┼┼┼█████████████████████████████");
            //Console.WriteLine("┼║┼║███▒┼┼┼║┼║┼┼█████████████████████████████");
            //Console.WriteLine("┼┼║▒██▒┼║┼┼┼║┼║┼▒████████████████████████████");
            //Console.WriteLine("┼║┼███┼┼┼┼┼║┼║┼║┼█████████║┼████████████████▒");
            //Console.WriteLine("║┼▒██┼║┼┼┼┼┼║┼┼┼║▒██████║┼║┼┼┼██████████████┼");
            //Console.WriteLine("┼║██▒┼┼║┼┼┼║┼┼┼┼┼┼▒███▒║┼║┼┼┼║┼█████████████┼");
            //Console.WriteLine("┼┼██┼┼┼┼┼┼┼┼┼┼┼┼║┼║┼┼┼║┼║┼║┼┼┼┼║███████████▒║");
            //Console.WriteLine("┼███┼║┼║┼┼┼┼┼║┼┼┼║┼┼┼┼┼┼┼║┼┼┼┼┼║███████████▒┼");
            //Console.WriteLine("┼██║┼┼║┼┼┼║┼┼┼║┼║┼┼┼║┼┼┼║┼║┼┼┼║┼║███████████║");
            //Console.WriteLine("║██┼┼┼┼║┼┼┼║┼║┼┼┼┼┼║┼║┼║┼┼┼┼┼║┼║┼▒███████┼██┼");
            //Console.WriteLine("▒██┼║┼║┼┼┼┼┼┼┼║┼┼┼┼┼┼┼┼┼┼┼║┼║┼┼┼║┼██████║┼██┼");
            //Console.WriteLine("███┼┼║┼║┼┼┼║┼║┼┼┼║┼║┼┼┼║┼║┼║┼║┼┼┼║┼████┼┼║██┼");
            //Console.WriteLine("██▒┼║┼║┼║┼┼┼┼┼║┼║┼┼┼║┼┼┼┼┼┼┼║┼║┼║┼┼┼║┼║┼┼┼██║");
            //Console.WriteLine("██▒┼┼┼┼┼┼┼┼║┼┼┼┼┼┼┼┼┼┼┼┼┼║┼┼┼┼┼║┼┼┼║┼║┼┼┼┼██┼");
            //Console.WriteLine("██▒┼┼┼║┼║┼┼┼║┼║┼┼┼║┼┼┼┼┼║┼┼┼║┼┼┼┼┼║┼║┼┼┼┼┼██║");
            //Console.WriteLine("██▒║┼║┼┼┼║┼┼┼┼┼┼┼┼┼║┼║┼┼┼┼┼║┼║┼║┼║┼║┼┼┼┼┼║██┼");
            //Console.WriteLine("██▒┼┼┼┼┼║┼║┼┼┼┼┼┼┼║┼║┼║┼║┼║┼┼┼║┼┼┼║┼┼┼┼┼┼┼██┼");
            //Console.WriteLine("▒██┼┼┼┼║┼┼┼┼┼┼┼║┼┼┼║┼┼┼┼┼┼┼┼┼║┼┼┼┼┼║┼║┼┼┼║██┼");
            //Console.WriteLine("▒██┼║┼┼┼┼┼║┼║┼║┼┼┼┼┼┼┼║┼║┼║┼║┼║┼┼┼┼┼┼┼┼┼┼┼██║");
            //Console.WriteLine("┼██┼┼┼┼║┼║┼┼┼┼┼║┼┼┼┼┼┼┼║┼║┼┼┼║┼║┼║┼║┼┼┼┼┼▒██┼");
            //Console.WriteLine("┼██▒┼┼║┼┼┼┼┼┼┼║┼┼┼┼┼┼┼║┼┼┼┼┼║┼┼┼║┼║┼║┼┼┼┼███║");
            //Console.WriteLine("┼▒██┼┼┼║┼║┼┼┼┼┼║┼║┼║┼┼┼║┼┼┼┼┼║┼║┼┼┼║┼║┼┼┼██▒┼");
            //Console.WriteLine("║┼██▒┼┼┼║┼║┼┼┼║┼▒▒▒┼║┼┼┼║┼▒▒▒┼║┼┼┼║┼║┼║┼▒██┼║");
            //Console.WriteLine("┼║███┼┼║┼┼┼║┼┼██████┼║┼║┼▒█████▒┼┼┼┼┼┼┼║███┼┼");
            //Console.WriteLine("║┼┼██▒║┼▒▒┼┼▒███████▒┼║┼┼████████┼║▒▒┼┼║██║┼║");
            //Console.WriteLine("┼║┼███┼┼┼████████████║┼┼▒███████████▒║┼███┼┼┼");
            //Console.WriteLine("┼┼┼┼███┼┼▒███████████┼┼┼███████████▒┼┼▒██┼║┼║");
            //Console.WriteLine("┼┼┼║▒██║█▒███████████▒┼┼███████████▒█┼██▒┼┼┼┼");
            //Console.WriteLine("║┼┼┼┼██▒▒█████████████║▒████████████▒║██║┼┼┼┼");
            //Console.WriteLine("┼┼┼║┼▒██┼█████████████┼▒████████████┼██▒┼║┼┼┼");
            //Console.WriteLine("┼┼║┼║┼██┼┼████████████║▒███████████┼┼██║┼┼┼┼┼");
            //Console.WriteLine("┼║┼║┼║██┼┼████████████┼▒███████████┼┼██║┼┼┼║┼");
            //Console.WriteLine("║┼┼┼┼┼██║┼███████████▒┼┼███████████┼┼██▒┼┼┼┼┼");
            //Console.WriteLine("┼┼┼┼┼║██┼┼▒██████████┼┼┼██████████▒║┼▒██┼║┼║┼");
            //Console.WriteLine("║┼┼┼║▒██┼┼║█████████║┼┼┼║█████████┼┼║┼██┼┼║┼║");
            //Console.WriteLine("┼║┼║┼▒██┼║┼║▒██████║┼║██┼║▒██████┼┼║┼┼██┼║┼┼┼");
            //Console.WriteLine("║┼┼┼║▒██┼┼┼┼┼┼▒▒║┼┼┼║███║┼║┼║▒▒┼║┼┼┼║┼██┼┼┼┼┼");
            //Console.WriteLine("┼┼┼║┼║██┼║┼┼┼║┼┼┼┼┼┼▒███║║┼┼┼┼┼┼┼┼┼┼┼▒██┼║┼┼┼");
            //Console.WriteLine("┼┼┼┼┼┼███┼┼┼┼┼║┼║┼║┼████┼┼┼┼┼┼┼┼║┼║┼┼██▒║┼┼┼┼");
            //Console.WriteLine("┼┼┼┼┼║┼███┼║┼║┼┼┼║┼┼┼▒█▒┼┼┼┼┼┼┼┼┼║┼▒███┼┼║┼┼┼");
            //Console.WriteLine("║┼║┼┼┼┼▒█████▒║┼┼┼║┼║┼┼┼┼┼┼┼║┼▒███████▒┼║┼┼┼┼");
            //Console.WriteLine("┼║┼┼┼┼┼┼▒███████┼║┼║┼┼┼┼┼║┼║┼████████▒┼║┼┼┼║┼");
            //Console.WriteLine("║┼┼┼║┼║┼║┼███████┼┼┼┼┼┼┼┼┼║┼▒██████▒┼┼║┼┼┼┼┼┼");
            //Console.WriteLine("┼┼┼║┼║┼┼┼┼┼║┼║▒███┼┼┼┼┼║┼┼┼┼███║┼║┼┼┼┼┼║┼║┼║┼");
            //Console.WriteLine("║┼┼┼┼┼║┼║┼║┼║┼║▒██║┼║┼║┼║┼║┼██┼┼║┼┼┼║┼┼┼┼┼║┼║");
            //Console.WriteLine("┼┼┼┼┼┼┼║┼┼┼║┼┼┼║███║┼┼┼┼┼║┼▒██┼┼┼║┼┼┼║┼║┼║┼║┼");
            //Console.WriteLine("║┼║┼┼┼┼┼┼┼┼┼║┼┼┼▒███▒▒▒║║▒████┼┼║┼║┼┼┼║┼┼┼║┼┼");
            //Console.WriteLine("┼┼┼║┼┼┼┼┼┼┼┼┼┼┼┼┼████████████║┼║┼║┼┼┼║┼║┼┼┼┼┼");
            //Console.WriteLine("║┼┼┼┼┼║┼║┼┼┼┼┼║┼┼┼▒████████▒║┼┼┼║┼║┼║┼║┼║┼║┼┼");
            Console.WriteLine("             `:+shdddho+ooo+/.                ");
            Console.WriteLine("          `:sdmmmmmmmmmdddmmmdho-             ");
            Console.WriteLine("         -yhhdmmmmmmdddhhhdddmmmds-           ");
            Console.WriteLine("        /hhhhdmmmddddhhhyyhhddddddh+.         ");
            Console.WriteLine("       :hhhhdddddddddhyyyyyyhhhdddhhs.        ");
            Console.WriteLine("      :hhhhhhhhhhddyo++os+osssshhyyhyo        ");
            Console.WriteLine("     .yyyyhhhhhhdh+----:/::+////os/ssy/       ");
            Console.WriteLine("    `yhy+ssssssyo-````.:...--.:-:syyhhy       ");
            Console.WriteLine("    +hhhhyyyyyyo.    `.````..`.`.-shhhy-      ");
            Console.WriteLine("   .hhhhhhhhhhs.    `.`    `` `.--:yyhy/      ");
            Console.WriteLine("   ohhhhhddhhh:`...::-.`   `  `...`.+hy+      ");
            Console.WriteLine("  .hdhhhddddhs`...``.--`      `:sho+:sh/      ");
            Console.WriteLine("  osdhhdddddd/  `./shdo:`     .yhy/.+yh-      ");
            Console.WriteLine(" :+hdhddmdoos+ `:ooyhyo.`      ::/-`.hs       ");
            Console.WriteLine(" s/ddddddd+:-:.``..//::`    `   ````.d-       ");
            Console.WriteLine("`yymdddddmdy-...````..`     ``````.`//        ");
            Console.WriteLine(" sdmdddddddhyyyy+.        `.-o/``...``        ");
            Console.WriteLine(" .hmddmddddyhhhdhy/-``      .+-./`  ``        ");
            Console.WriteLine("  .dddmdddddyssssshhys/...``-+shd+` -+.       ");
            Console.WriteLine("   odddddhhhhdyyyyhhhhs:..``shdddy+:+oo-`     ");
            Console.WriteLine("   `/ohdhhhhhhhyyyhhyhys+///hhhhhssooosyo/`   ");
            Console.WriteLine("     .-osyyyyyhyyyhyyssssooshhhddyyssssssyo`  ");
            Console.WriteLine("       `.:yyyyhyhhyyyosssososddhhysyyysossys. ");
            Console.WriteLine("        .syyyyhyyyyyyssososssydhyssyyssyssshs`");
            Console.WriteLine("       .osyhyyhhyyysyssysssyssshysyhhssysyshh`");
            Console.WriteLine("      `osyshhyhhhyyyysysysssssyysyhhysysyyyyo ");
            Console.WriteLine("     `oysyyhhhdhhyyyysyssssysssyyyhhyyyso/-`  ");
            Thread.Sleep(2000);
            //Process.Start("getData_App.exe");
            System.Diagnostics.Process.Start("getData_App.exe");
            Thread.Sleep(1000);

        }
    }
}
